// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetSensorData = { lowest_added_at: number | null, upper_added_at: number | null, id: string, };
