// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiUser = { username: string, email: string, created_at: number, updated_at: number, };
