// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Register User
 */
export type PostUser = { username: string, hashed_password: string, email: string, };
