// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiColor } from "../../types/ApiColor";
import type { ApiDescription } from "../../types/ApiDescription";
import type { ApiEntityName } from "../../types/ApiEntityName";
import type { ApiPubKey } from "../../types/ApiPubKey";
import type { DeviceId } from "../../types/DeviceId";

export type ApiUserSensor = { device_id: DeviceId, pub_key: ApiPubKey, name: ApiEntityName, description: ApiDescription | null, color: ApiColor, created_at: number, updated_at: number, place_name: ApiEntityName, };
