// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaceChange } from "../../../PlaceChange";
import type { ApiEntityName } from "../../types/ApiEntityName";

export type PutPlace = { place_name: ApiEntityName, change: PlaceChange, };
