// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiColor } from "../../types/ApiColor";
import type { ApiDescription } from "../../types/ApiDescription";
import type { ApiEntityName } from "../../types/ApiEntityName";

export type PostPlace = { name: ApiEntityName, description: ApiDescription | null, color: ApiColor, };
