// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiEmail } from "../../types/ApiEmail";
import type { ApiUsername } from "../../types/ApiUsername";

export type ApiUser = { username: ApiUsername, email: ApiEmail, created_at: number, updated_at: number, };
