// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiEmail } from "../../types/ApiEmail";
import type { ApiRawPassword } from "../../types/ApiRawPassword";
import type { ApiUsername } from "../../types/ApiUsername";

/**
 * Register User
 */
export type PostUser = { username: ApiUsername, raw_password: ApiRawPassword, email: ApiEmail, };
