// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiSession } from "../session/ApiSession";
import type { ApiUser } from "./ApiUser";

export type PutUserResponse = { updated: ApiUser, new_session: ApiSession, };
