// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceId } from "../../types/DeviceId";

export type GetSensorData = { device_id: DeviceId, lowest_added_at: number | null, upper_added_at: number | null, };
