// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiSession } from "../session/ApiSession";
import type { ApiSensorData } from "./ApiSensorData";

export type PostSensorDataResponse = { api_data: ApiSensorData, new_session: ApiSession, };
