// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Aht10Data } from "./Aht10Data";
import type { Scd4xData } from "./Scd4xData";

export type AnySensorData = { "sensor_type": "Aht10" } & Aht10Data | { "sensor_type": "Scd4x" } & Scd4xData;
