// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlaceColor = "HEX_403E2A" | "HEX_807895" | "HEX_2A4039" | "HEX_402E2A" | "HEX_957E78" | "HEX_302A40" | "HEX_807E71" | "HEX_78958B" | "HEX_BFBA7A" | "HEX_EA937D";
