// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiId } from "./ApiId";
import type { PlaceColor } from "./PlaceColor";

export type PlaceSummary = { place_id: ApiId, last_update: number, name: string, description: string | null, color: PlaceColor, };
