// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiId } from "./ApiId";
import type { SensorKind } from "./SensorKind";

export type SensorSummary = { kind: SensorKind, api_id: ApiId, device_id: ApiId, last_update: number, place: number, };
