// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SensorColor =
  | "HEX_DB2122"
  | "HEX_F0D16F"
  | "HEX_21DB55"
  | "HEX_2132DB"
  | "HEX_6FF0D1"
  | "HEX_DB21A0"
  | "HEX_DB8F21";
