// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaceSummary } from "./PlaceSummary";
import type { SensorSummary } from "./SensorSummary";

export type UserSummary = { username: string, email: string, sensors: Array<SensorSummary>, places: Array<PlaceSummary>, };
