// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiId } from "../ApiId";
import type { SensorKind } from "../SensorKind";

export type GetSensorDataRequestBody = { user_api_id: ApiId, sensor_api_id: ApiId, added_at_upper: number | null, added_at_lower: number | null, };

export type GetSensorDataResponseBody = { item_count: number, serialized_data: Array<[string, number]>, sensor_kind: SensorKind, };

export type GetSensorDataResponseCode = "Ok" | "BadRequest" | "PayloadTooLarge" | "Unauthorized" | "InternalServerError";
