// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiId } from "../ApiId";

export type LoginRequestBody = { username: string, hashed_password: string, };

export type LoginResponseBody = { api_id: ApiId, };

export type LoginResponseCode = "Ok" | "BadRequest" | "PayloadTooLarge" | "Unauthorized" | "InternalServerError";
