// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiId } from "../ApiId";
import type { SensorColor } from "../SensorColor";
import type { SensorKind } from "../SensorKind";

export type PostSensorRequestBody = { "CreateSensor": { user_api_id: ApiId, user_place_id: ApiId, device_id: ApiId, sensor_kind: SensorKind, sensor_name: string, sensor_description: string | null, sensor_color: SensorColor, } } | { "DeleteSensor": { user_api_id: ApiId, sensor_api_id: ApiId, } };

export type PostSensorResponseBody = { sensor_api_id: string, };

export type PostSensorResponseCode = "Ok" | "BadRequest" | "PayloadTooLarge" | "Unauthorized" | "InternalServerError";
