// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiId } from "../ApiId";
import type { PlaceColor } from "../PlaceColor";

export type PostPlaceRequestBody = { "Create": { username: string, user_api_id: ApiId, place_name: string, place_description: string | null, place_color: PlaceColor, } } | { "Delete": { user_api_id: ApiId, place_id: ApiId, } };

export type PostPlaceResponseBody = { "Created": { place_id: ApiId, place_name: string, place_description: string | null, } } | "NoContent";

export type PostPlaceResponseCode = "Ok" | "BadRequest" | "PayloadTooLarge" | "Unauthorized" | "InternalServerError" | "NoContent";
