// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiId } from "../ApiId";
import type { SensorKind } from "../SensorKind";

export type PostSensorRequestBody = { user_api_id: ApiId, user_place_id: number, device_id: ApiId, sensor_kind: SensorKind, };

export type PostSensorResponseBody = { sensor_api_id: string, };

export type PostSensorResponseCode = "Ok" | "BadRequest" | "PayloadTooLarge" | "Unauthorized" | "InternalServerError";
