// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnySensorData } from "../AnySensorData";
import type { ApiId } from "../ApiId";

export type PostSensorDataRequestBody = { user_api_id: ApiId, sensor_api_id: ApiId, data: AnySensorData, added_at: number | null, };

export type PostSensorResponseCode = "Ok" | "BadRequest" | "Unauthorized" | "PayloadTooLarge" | "InternalServerError";
