// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiId } from "../ApiId";
import type { UserSummary } from "../UserSummary";

export type PostUserSummaryRequestBody = { username: string, user_api_id: ApiId, };

export type PostUserSummaryResponseBody = { summary: UserSummary, };

export type PostUserSummaryResponseCode = "Ok" | "BadRequest" | "PayloadTooLarge" | "Unauthorized" | "InternalServerError";
