// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiId } from "../ApiId";

export type RegisterIncorrectReason = "EmailUsed" | "UsernameUsed" | "HashInvalid";

export type RegisterRequestBody = { username: string, hashed_password: string, email: string, };

export type RegisterResponseBody = { "Correct": ApiId } | { "Incorrect": RegisterIncorrectReason };

export type RegisterResponseCode = "Ok" | "BadRequest" | "PayloadTooLarge" | "Unauthorized" | "InternalServerError";
