// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceId } from "../../types/DeviceId";

export type ApiUserSensor = { device_id: DeviceId, name: string, description: string | null, color: string, created_at: number, updated_at: number, };
