// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiSensorData } from "../sensor_data/ApiSensorData";
import type { ApiUserSensor } from "./ApiUserSensor";

export type GetSensorResponse = { sensor: ApiUserSensor, last_data: ApiSensorData | null, };
