// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SensorChange } from "../../../SensorChange";
import type { DeviceId } from "../../types/DeviceId";

export type PutSensor = { device_id: DeviceId, change: SensorChange, };
