-- This file should undo anything in `up.sql`
DROP TABLE IF EXISTS sensor_color CASCADE;
DROP TABLE IF EXISTS place_color CASCADE;
DROP TABLE IF EXISTS sensor_data CASCADE;
DROP TABLE IF EXISTS user_sensors CASCADE;
DROP TABLE IF EXISTS sensor_kinds CASCADE;
DROP TABLE IF EXISTS user_places CASCADE;
DROP TABLE IF EXISTS users CASCADE;