// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceId } from "../../types/DeviceId";

export type GetSensor = { "FromSensorDeviceId": DeviceId } | { "FromPlaceName": string };
