// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiRawPassword } from "../../types/ApiRawPassword";
import type { ApiUsername } from "../../types/ApiUsername";

export type PostSession = { username: ApiUsername, raw_password: ApiRawPassword, };
