// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiColor } from "./api/types/ApiColor";
import type { ApiDescription } from "./api/types/ApiDescription";
import type { ApiEntityName } from "./api/types/ApiEntityName";

export type SensorChange = { "PlaceName": ApiEntityName } | { "Name": ApiEntityName } | { "Description": ApiDescription | null } | { "Color": ApiColor };
