// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiSession = { access_token: string, expires_in: number, token_type: string, };
