// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceId } from "../../types/DeviceId";

export type SensorLogin = { device_id: DeviceId, random_message_encoded: string, signature_of_message: string, };
